package com.example.playground.common

enum class OrderState(val value: String) {
    INITIALIZED("INITIALIZED"),
    PULLABLE("PULLABLE"),
    SUBMITTABLE_PENDING_PAYMENT("SUBMITTABLE_PENDING_PAYMENT"),
    SUBMITTABLE("SUBMITTABLE"),
    PULLED("PULLED"),
    SUBMITTED_PENDING_PAYMENT("SUBMITTED_PENDING_PAYMENT"),
    SUBMITTED("SUBMITTED"),
    FULFILLING_SUBMITTABLE_PENDING_PAYMENT("FULFILLING_SUBMITTABLE_PENDING_PAYMENT"),
    FULFILLING_SUBMITTABLE("FULFILLING_SUBMITTABLE"),
    FULFILLING_WAITING("FULFILLING_WAITING"),
    FULFILLING_SUBMITING("FULFILLING_SUBMITING"),
    FULFILLING_PREPARING("FULFILLING_PREPARING"),
    FULFILLING_READY("FULFILLING_READY"),
    FULFILLING_SERVING_PENDING_FULFILLMENT_AREA("FULFILLING_SERVING_PENDING_FULFILLMENT_AREA"),
    FULFILLING_SERVING("FULFILLING_SERVING"),
    MONITORING_FOR_RECONCILIATION("MONITORING_FOR_RECONCILIATION"),
    FULFILLED_PENDING_PAYMENT_REVERSAL("FULFILLED_PENDING_PAYMENT_REVERSAL"),
    FAILED_TO_FULFILL_PENDING_PAYMENT_REVERSAL("FAILED_TO_FULFILL_PENDING_PAYMENT_REVERSAL"),
    CANCELLED_PENDING_PAYMENT_REVERSAL("CANCELLED_PENDING_PAYMENT_REVERSAL"),
    FULFILLED("FULFILLED"),
    FAILED_TO_FULFILL("FAILED_TO_FULFILL"),
    CANCELLED("CANCELLED");
}
